name: aplikasi_absen_wrapper
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  
  # Diubah ke ^6.0.0 karena versi ini resmi ada di pub.dev dan cocok untuk Dart 3.4.4
  flutter_inappwebview: ^6.0.0
  device_info_plus: ^13.1.0
  local_auth: ^3.0.1
  geolocator: ^14.0.3
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true